CREATE TABLE TRANSACTION (
      TRANSACTION_ID INTEGER NOT NULL AUTO_INCREMENT,
      TRANSACTION_DATE TIMESTAMP NOT NULL,
      NOTES  VARCHAR(200),
      GALLONS  DOUBLE NOT NULL,
	  COST_PER_GALLON DOUBLE NOT NULL,
      TOTAL_COST  DOUBLE NOT NULL,
      MILEAGE  INTEGER NOT NULL,
      CC_USER  VARCHAR(20) NOT NULL,
      RECEIPT BLOB,
      LAST_UPDATED_TIME TIMESTAMP,
      CONSTRAINT TRANSACTION_PK Primary Key (TRANSACTION_ID)
);