CREATE TABLE TRANSACTION (
      TRANSACTION_ID INTEGER NOT NULL ,
      TRANSACTION_DATE TIMESTAMP NOT NULL,
      NOTES  VARCHAR(200),
      GALLONS  DOUBLE(2,2) NOT NULL,
	  COST_PER_GALLON DOUBLE(2,2) NOT NULL,
      TOTAL_COST  DOUBLE(2,2) NOT NULL,
      MILEAGE  INTEGER NOT NULL,
      CC_USER  VARCHAR(20) NOT NULL,
      RECEIPT BLOB,
      LAST_UPDATED_TIME TIMESTAMP
);


ALTER TABLE TRANSACTION ADD CONSTRAINT TRANSACTION_PK Primary Key (TRANSACTION_ID);